export default [
  {
    Month: "January",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 5000,
  },
  {
    Month: "January",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 3000,
  },
  {
    Month: "January",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 4000,
  },
  {
    Month: "January",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 2000,
  },
  {
    Month: "February",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 6000,
  },
  {
    Month: "February",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 3500,
  },
  {
    Month: "February",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 4500,
  },
  {
    Month: "February",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 2500,
  },
  {
    Month: "March",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 7000,
  },
  {
    Month: "March",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 4000,
  },
  {
    Month: "March",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 5000,
  },
  {
    Month: "March",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 3000,
  },
  {
    Month: "April",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 7500,
  },
  {
    Month: "April",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 4500,
  },
  {
    Month: "April",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 5500,
  },
  {
    Month: "April",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 3500,
  },
  {
    Month: "May",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 8000,
  },
  {
    Month: "May",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 5000,
  },
  {
    Month: "May",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 6000,
  },
  {
    Month: "May",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 4000,
  },
  {
    Month: "June",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 8500,
  },
  {
    Month: "June",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 5500,
  },
  {
    Month: "June",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 6500,
  },
  {
    Month: "June",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 4500,
  },
  {
    Month: "July",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 9000,
  },
  {
    Month: "July",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 6000,
  },
  {
    Month: "July",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 7000,
  },
  {
    Month: "July",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 5000,
  },
  {
    Month: "August",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 9500,
  },
  {
    Month: "August",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 6500,
  },
  {
    Month: "August",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 7500,
  },
  {
    Month: "August",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 5500,
  },
  {
    Month: "September",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 10000,
  },
  {
    Month: "September",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 7000,
  },
  {
    Month: "September",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 8000,
  },
  {
    Month: "September",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 6000,
  },
  {
    Month: "October",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 10500,
  },
  {
    Month: "October",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 7500,
  },
  {
    Month: "October",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 8500,
  },
  {
    Month: "October",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 6500,
  },
  {
    Month: "November",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 11000,
  },
  {
    Month: "November",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 8000,
  },
  {
    Month: "November",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 9000,
  },
  {
    Month: "November",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 7000,
  },
  {
    Month: "December",
    Region: "North",
    ProductCategory: "Electronics",
    SalesRep: "Alice",
    SalesAmount: 11500,
  },
  {
    Month: "December",
    Region: "North",
    ProductCategory: "Furniture",
    SalesRep: "Bob",
    SalesAmount: 8500,
  },
  {
    Month: "December",
    Region: "South",
    ProductCategory: "Electronics",
    SalesRep: "Charlie",
    SalesAmount: 9500,
  },
  {
    Month: "December",
    Region: "South",
    ProductCategory: "Furniture",
    SalesRep: "Dave",
    SalesAmount: 7500,
  },
];
